config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :user_stories
  resources :milestones
  resources :projects
  resources :memberships
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/user_story.rb
class UserStory < ApplicationRecord

  validates: descriptive_name, presence: true
  
  belongs_to :project

  has_many :issues
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :set_user_story, only: %i[ show edit update destroy ]

  # GET /user_stories or /user_stories.json
  def index
    @user_stories = UserStory.all
  end

  # GET /user_stories/1 or /user_stories/1.json
  def show
  end

  # GET /user_stories/new
  def new
    @user_story = UserStory.new
  end

  # GET /user_stories/1/edit
  def edit
  end

  # POST /user_stories or /user_stories.json
  def create
    @user_story = UserStory.new(user_story_params)

    respond_to do |format|
      if @user_story.save
        format.html { redirect_to user_story_url(@user_story), notice: "User story was successfully created." }
        format.json { render :show, status: :created, location: @user_story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stories/1 or /user_stories/1.json
  def update
    respond_to do |format|
      if @user_story.update(user_story_params)
        format.html { redirect_to user_story_url(@user_story), notice: "User story was successfully updated." }
        format.json { render :show, status: :ok, location: @user_story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stories/1 or /user_stories/1.json
  def destroy
    @user_story.destroy

    respond_to do |format|
      format.html { redirect_to user_stories_url, notice: "User story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_story_params
      params.require(:user_story).permit(:milestone_id, :descriptive_name, :membership_id, :project_id, :estimated_completion_date)
    end
end

app/views/user_stories/_form.html.erb
<%= form_with(model: user_story) do |form| %>
  <% if user_story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_story.errors.count, "error") %> prohibited this user_story from being saved:</h2>

      <ul>
        <% user_story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :milestone_id, style: "display: block" %>
    <%= form.number_field :milestone_id %>
  </div>

  <div>
    <%= form.label :descriptive_name, style: "display: block" %>
    <%= form.text_area :descriptive_name %>
  </div>

  <div>
    <%= form.label :membership_id, style: "display: block" %>
    <%= form.number_field :membership_id %>
  </div>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.number_field :project_id %>
  </div>

  <div>
    <%= form.label :estimated_completion_date, style: "display: block" %>
    <%= form.date_field :estimated_completion_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_stories/_user_story.html.erb
<div id="<%= dom_id user_story %>">
  <p>
    <strong>Milestone:</strong>
    <%= user_story.milestone_id %>
  </p>

  <p>
    <strong>Descriptive name:</strong>
    <%= user_story.descriptive_name %>
  </p>

  <p>
    <strong>Membership:</strong>
    <%= user_story.membership_id %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= user_story.project_id %>
  </p>

  <p>
    <strong>Estimated completion date:</strong>
    <%= user_story.estimated_completion_date %>
  </p>

</div>

app/views/user_stories/edit.html.erb
<h1>Editing user story</h1>

<%= render "form", user_story: @user_story %>

<br>

<div>
  <%= link_to "Show this user story", @user_story %> |
  <%= link_to "Back to user stories", user_stories_path %>
</div>

app/views/user_stories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User stories</h1>

<div id="user_stories">
  <% @user_stories.each do |user_story| %>
    <%= render user_story %>
    <p>
      <%= link_to "Show this user story", user_story %>
    </p>
  <% end %>
</div>

<%= link_to "New user story", new_user_story_path %>

app/views/user_stories/new.html.erb
<h1>New user story</h1>

<%= render "form", user_story: @user_story %>

<br>

<div>
  <%= link_to "Back to user stories", user_stories_path %>
</div>

app/views/user_stories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_story %>

<div>
  <%= link_to "Edit this user story", edit_user_story_path(@user_story) %> |
  <%= link_to "Back to user stories", user_stories_path %>

  <%= button_to "Destroy this user story", @user_story, method: :delete %>
</div>