config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :user_stories
  resources :milestones
  resources :projects
  resources :memberships
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id                        :integer          not null, primary key
#  descriptive_name          :text
#  estimated_completion_date :date
#  status                    :text
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  project_id                :integer
#
class Milestone < ApplicationRecord

  validates :descriptive_name, presence: true

  belongs_to :project
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: %i[ show edit update destroy ]

  # GET /milestones or /milestones.json
  def index
    @milestones = Milestone.all
  end

  # GET /milestones/1 or /milestones/1.json
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones or /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to milestone_url(@milestone), notice: "Milestone was successfully created." }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1 or /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to milestone_url(@milestone), notice: "Milestone was successfully updated." }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1 or /milestones/1.json
  def destroy
    @milestone.destroy

    respond_to do |format|
      format.html { redirect_to milestones_url, notice: "Milestone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def milestone_params
      params.require(:milestone).permit(:project_id, :estimated_completion_date, :descriptive_name, :status)
    end
end

app/views/milestones/_form.html.erb
<%= form_with(model: milestone) do |form| %>
  <% if milestone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
        <% milestone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.number_field :project_id %>
  </div>

  <div>
    <%= form.label :estimated_completion_date, style: "display: block" %>
    <%= form.date_field :estimated_completion_date %>
  </div>

  <div>
    <%= form.label :descriptive_name, style: "display: block" %>
    <%= form.text_area :descriptive_name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_area :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/milestones/_milestone.html.erb
<div id="<%= dom_id milestone %>">
  <p>
    <strong>Project:</strong>
    <%= milestone.project_id %>
  </p>

  <p>
    <strong>Estimated completion date:</strong>
    <%= milestone.estimated_completion_date %>
  </p>

  <p>
    <strong>Descriptive name:</strong>
    <%= milestone.descriptive_name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= milestone.status %>
  </p>

</div>

app/views/milestones/edit.html.erb
<h1>Editing milestone</h1>

<%= render "form", milestone: @milestone %>

<br>

<div>
  <%= link_to "Show this milestone", @milestone %> |
  <%= link_to "Back to milestones", milestones_path %>
</div>

app/views/milestones/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Milestones</h1>

<div id="milestones">
  <% @milestones.each do |milestone| %>
    <%= render milestone %>
    <p>
      <%= link_to "Show this milestone", milestone %>
    </p>
  <% end %>
</div>

<%= link_to "New milestone", new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New milestone</h1>

<%= render "form", milestone: @milestone %>

<br>

<div>
  <%= link_to "Back to milestones", milestones_path %>
</div>

app/views/milestones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @milestone %>

<div>
  <%= link_to "Edit this milestone", edit_milestone_path(@milestone) %> |
  <%= link_to "Back to milestones", milestones_path %>

  <%= button_to "Destroy this milestone", @milestone, method: :delete %>
</div>