config/routes.rb
Rails.application.routes.draw do
  resources :issues
  resources :user_stories
  resources :milestones
  resources :projects
  resources :memberships
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id                     :integer          not null, primary key
#  description            :text
#  resolution_explanation :text
#  status                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  task_id                :integer
#
class Issue < ApplicationRecord

  validates :description, presence: true

  belongs_to :user_story
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[ show edit update destroy ]

  # GET /issues or /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issue_url(@issue), notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to issue_url(@issue), notice: "Issue was successfully updated." }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:description, :task_id, :status, :resolution_explanation)
    end
end

app/views/issues/_form.html.erb
<%= form_with(model: issue) do |form| %>
  <% if issue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.number_field :task_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :resolution_explanation, style: "display: block" %>
    <%= form.text_area :resolution_explanation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/_issue.html.erb
<div id="<%= dom_id issue %>">
  <p>
    <strong>Description:</strong>
    <%= issue.description %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= issue.task_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= issue.status %>
  </p>

  <p>
    <strong>Resolution explanation:</strong>
    <%= issue.resolution_explanation %>
  </p>

</div>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render "form", issue: @issue %>

<br>

<div>
  <%= link_to "Show this issue", @issue %> |
  <%= link_to "Back to issues", issues_path %>
</div>

app/views/issues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Issues</h1>

<div id="issues">
  <% @issues.each do |issue| %>
    <%= render issue %>
    <p>
      <%= link_to "Show this issue", issue %>
    </p>
  <% end %>
</div>

<%= link_to "New issue", new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render "form", issue: @issue %>

<br>

<div>
  <%= link_to "Back to issues", issues_path %>
</div>

app/views/issues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @issue %>

<div>
  <%= link_to "Edit this issue", edit_issue_path(@issue) %> |
  <%= link_to "Back to issues", issues_path %>

  <%= button_to "Destroy this issue", @issue, method: :delete %>
</div>